config_type: "prediction" # options: data_preprocessor, prediction, evaluation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/coronaviridae"

  # Name of file(s) in subdirectory to be read and processed.
  # Example: file_names: ["file_1.csv", "file_2.csv", "file_3.csv"]
  file_names: [ "coronaviridae_final.csv" ]
  # seeds to split the files into training and testing
  # if provided, the number of seeds must match the number of iterations configured in classification_settings (n_iterations)
  split_seeds: [ "s12612648", "s31062180", "s48918293", "s55631155", "s79221635" ]


classification_settings:
  model_type: "nlp"
  n_iterations: 5
  split_input: False
  type: "multi"
  sequence_settings:
    batch_size: 32
    sequence_col: "seq"
    max_sequence_length: 1453 # max=1453
    truncate: False
    pad_sequence_val: 0
  label_settings:
    label_col: "virus_host"
    exclude_labels: [ "nan"]
    label_groupings:
      "Pig": ["Sus scrofa (Pig) [TaxID: 9823]"]
      "Human": ["Homo sapiens (Human) [TaxID: 9606]"]
      "Wild turkey": ["Meleagris gallopavo (Wild turkey) [TaxID: 9103]"]
      "Japanese pipistrelle": ["Pipistrellus abramus (Japanese pipistrelle) (Pipistrellus javanicus abramus) [TaxID: 105295]"]
      "Lesser bamboo bat": ["Tylonycteris pachypus (Lesser bamboo bat) (Vespertilio pachypus) [TaxID: 258959]"]
      "Chicken": ["Gallus gallus (Chicken) [TaxID: 9031]"]
      "Bovine": ["Bos taurus (Bovine) [TaxID: 9913]"]

  models:
    - name: "transformer-crossentropy"
      active: False
      mode: train # supported values: train, test
      pretrained_model_path: #"output/raw/uniref90/20230407/host_multi/trained_transformer_model.pth" # mandatory if the mode is set to test
      loss: "CrossEntropyLoss"
      with_convolution: False # ensure that truncate is set to True in sequence_settings if convolution is not being used
      n_heads: 8
      depth: 6
      n_tokens: 27
      n_classes: 7
      n_epochs: 10
      dim: 512

    - name: "transformer-conv1d-crossentropy"
      active: True
      mode: train # supported values: train, test
      pretrained_model_path: #"output/raw/uniref90/20230407/host_multi/trained_transformer_model.pth" # mandatory if the mode is set to test
      loss: "CrossEntropyLoss"
      with_convolution: True # ensure that truncate is set to False in sequence_settings if convolution is being used
      kernel_size: 3
      stride: 1
      padding: 0
      n_heads: 8
      depth: 6
      n_tokens: 27
      n_classes: 7
      n_epochs: 10
      dim: 512

output_settings:
  output_dir: "output"
  results_dir: "raw"
  visualizations_dir: "visualization"
  sub_dir: "coronaviridae/20230503/host_multi"
  prefix: "tf-cnv-ce-k3s1-d512-top7" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv
