config_type: "prediction" # options: data_preprocessor, prediction, evaluation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/coronaviridae"

  # Name of file(s) in subdirectory to be read and processed.
  # Example: file_names: ["file_1.csv", "file_2.csv", "file_3.csv"]
  file_names: ["coronaviridae_top_7_hosts.csv"]
  # seeds to split the files into training and testing
  # if provided, the number of seeds must match the number of iterations configured in classification_settings (n_iterations)
  split_seeds: [ 12612648, 31062180, 48918293, 55631155, 79221635 ]



classification_settings:
  model_type: "nlp"
  n_iterations: 5
  split_input: True
  train_proportion: 0.8
  type: "multi"
  sequence_settings:
    batch_size: 8
    id_col: "id"
    sequence_col: "seq"
    max_sequence_length: 1453 # max=1453
    truncate: True
    pad_sequence_val: 0
    feature_type: "token"  # supported values 'kmer', 'cgr', 'tokens'
    kmer_settings:
      k: 3
    cgr_settings:
      img_size: 8
      img_dir: "input/data/coronaviridae/cgr_images"
  training_settings:
    n_epochs: 10
    max_lr: 1e-4
    pct_start: 0.10
    div_factor: 25.0
    final_div_factor: 10000.0
  label_settings:
    label_col: "virus_host"
    exclude_labels: [ "nan"]
    label_groupings:
      "Pig": [ "Sus scrofa (Pig) [TaxID: 9823]" ]
      "Human": [ "Homo sapiens (Human) [TaxID: 9606]" ]
      "Wild turkey": [ "Meleagris gallopavo (Wild turkey) [TaxID: 9103]" ]
      "Japanese pipistrelle": [ "Pipistrellus abramus (Japanese pipistrelle) (Pipistrellus javanicus abramus) [TaxID: 105295]" ]
      "Lesser bamboo bat": [ "Tylonycteris pachypus (Lesser bamboo bat) (Vespertilio pachypus) [TaxID: 258959]" ]
      "Chicken": [ "Gallus gallus (Chicken) [TaxID: 9031]" ]
      "Bovine": [ "Bos taurus (Bovine) [TaxID: 9913]" ]
  models:
    - name: "fnn-l_10"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 10
      n_tokens: 27
      n_classes: 7
      n_epochs: 50
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "kmer-fnn-l_10"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 10
      n_tokens: 27
      n_classes: 9
      n_epochs: 10
      hidden_dim: 1024
      manual_seed:  # whole numbersgit

    - name: "cnn-l_4"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 4
      n_tokens: 27
      n_classes: 7
      n_epochs: 50
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      kernel_size: 3
      stride: 1
      manual_seed:  # whole numbers

    - name: "cgr-cnn-l_2"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 2
      n_tokens: 27
      n_classes: 7
      n_epochs: 10
      n_filters: 3
      kernel_size: 3
      stride: 1
      manual_seed:  # whole numbers

    - name: "rnn-l_6"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 6 # number of rnn layers
      n_tokens: 27
      n_classes: 7
      n_epochs: 10
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "lstm-l_2"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 2
      n_tokens: 27
      n_classes: 7
      n_epochs: 50
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "transformer-l_6-h_8"
      active: True
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      with_convolution: False
      n_heads: 8
      depth: 6
      n_tokens: 27
      n_classes: 7
      n_epochs: 50
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "transformer-conv-k4s4"
      active: False
      mode: "train" # supported values: train, test
      pretrained_model_path: #"output/raw/uniref90/20230407/host_multi/trained_transformer_model.pth" # mandatory if the mode is set to test
      loss: "FocalLoss"
      with_convolution: True # ensure that truncate is set to False in sequence_settings if convolution is being used
      kernel_size: 4
      stride: 4
      padding: 0
      n_heads: 8
      depth: 6
      n_tokens: 27
      n_classes: 7
      n_epochs: 10
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed: 0 # whole numbers
output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "coronaviridae/20230908/host_multi_baseline_focal_pytorchtf"
  prefix: "emb_sincos-d_1024-loss_focalce" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv