config_type: "prediction" # options: data_preprocessor, prediction, evaluation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  perturbed_dataset_dir: "input/data/coronaviridae/perturbed_dataset/sarscov2-S-WIV04"

classification_settings:
  model_type: "perturbed_dataset_prediction"  # options: baseline, nlp, perturbed_dataset_prediction
  type: "multi"
  sequence_settings:
    batch_size: 32
    id_col: "id"
    sequence_col: "seq"
    max_sequence_length: 1453 # max=1453
    truncate: False
    pad_sequence_val: 0
    feature_type: "token"  # supported values 'kmer', 'cgr', 'token'
    kmer_settings:
      k: 3
    cgr_settings:
      img_size: 8
      img_dir: "input/data/coronaviridae/cgr_images"

  label_settings:
    label_col: "virus_host"
    exclude_labels: [ "nan"]
    label_groupings:
      "Pig": [ "Sus scrofa (Pig) [TaxID: 9823]" ]
      "Human": [ "Homo sapiens (Human) [TaxID: 9606]" ]
      "Wild turkey": [ "Meleagris gallopavo (Wild turkey) [TaxID: 9103]" ]
      "Japanese pipistrelle": [ "Pipistrellus abramus (Japanese pipistrelle) (Pipistrellus javanicus abramus) [TaxID: 105295]" ]
      "Lesser bamboo bat": [ "Tylonycteris pachypus (Lesser bamboo bat) (Vespertilio pachypus) [TaxID: 258959]" ]
      "Chicken": [ "Gallus gallus (Chicken) [TaxID: 9031]" ]
      "Bovine": [ "Bos taurus (Bovine) [TaxID: 9913]" ]
  models:
    - name: "fnn-l_10-lr1e-4"
      active: False
      mode: "test" # supported values: train, test
      model_path: ""
      loss: "FocalLoss"
      depth: 10
      n_tokens: 27
      n_classes: 7
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "kmer-fnn-l_10"
      active: False
      mode: "test" # supported values: train, test
      model_path: ""
      loss: "FocalLoss"
      depth: 10
      n_tokens: 27
      n_classes: 9
      n_epochs: 10
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "cnn-l_4-lr1e-4"
      active: True
      mode: "test" # supported values: train, test
      model_path: "output/raw/coronaviridae/20230908/host_multi_lr1e-3-e50/cnn-l_4-lr1e-3_itr0.pth"
      loss: "FocalLoss"
      depth: 4
      n_tokens: 27
      n_classes: 7
      n_epochs: 50
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      kernel_size: 3
      stride: 1
      manual_seed:  # whole numbers

    - name: "cgr-cnn-l_2-lr1e-4"
      active: False
      mode: "test" # supported values: train, test
      model_path: ""
      loss: "FocalLoss"
      depth: 2
      n_tokens: 27
      n_classes: 7
      n_filters: 3
      kernel_size: 3
      stride: 1
      manual_seed:  # whole numbers

    - name: "rnn-l_6-lr1e-4"
      active: False
      mode: "test" # supported values: train, test
      model_path: ""
      loss: "FocalLoss"
      depth: 6 # number of rnn layers
      n_tokens: 27
      n_classes: 7
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "lstm-l_2-lr1e-4"
      active: False
      mode: "test" # supported values: train, test
      model_path: "output/raw/coronaviridae/20230908/host_multi_lr1e-3-e50/lstm-l_2-lr1e-3_itr0.pth"
      loss: "FocalLoss"
      depth: 2
      n_tokens: 27
      n_classes: 7
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "transformer-l_6-h_8-lr1e-4"
      active: False
      mode: "test" # supported values: train, test
      model_path: "output/raw/coronaviridae/20230908/host_multi_lr1e-4-e50/transformer-custom-l_6-h_8-lr1e-4_itr0.pth"
      loss: "FocalLoss"
      with_convolution: False
      n_heads: 8
      depth: 6
      n_tokens: 27
      n_classes: 7
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "coronaviridae/sarscov2-S-WIV04/20230917/perturbed_dataset_prediction/cnn-l_4-lr1e-4"
  prefix: "cnn" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv