config_type: "transfer_learning" # options: data_preprocessor, host_prediction, evaluation, transfer_learning
config_sub_type: "host_prediction_external"

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/uniref90/20240131"

  # Name of file(s) in subdirectory to be read and processed.
  # Example: file_names: ["file_1.csv", "file_2.csv", "file_3.csv"]
  # file_names: [ "uniref90_final_msl1114.csv" ]
  file_names: [ "uniref90_viridae_embl_hosts_pruned_metadata_species_vertebrates_w_seq_non_idv_t0.01_c5_seq_len_in_99.9percentile.csv" ]
  # seeds to split the files into training and testing
  # if provided, the number of seeds must match the number of iterations configured in classification_settings (n_iterations)
  split_seeds: [ 55631155 ] # [ 12612648, 31062180, 48918293, 55631155, 79221635 ] #

sequence_settings:
    batch_size: 8
    id_col: "uniref90_id"
    sequence_col: "seq"
    truncate: True
    max_sequence_length: 2048
    split_sequence: False
    feature_type: "token"  # supported values 'kmer', 'cgr', 'token'

fine_tune_settings:
  experiment: "external"
  n_iterations: 1
  split_input: True
  train_proportion: 0.8
  classification_type: "multi"
  save_model: True

  training_settings:
    n_epochs: 50
    max_lr: 3e-4
    pct_start: 0.10
    div_factor: 25.0
    final_div_factor: 10000.0

  label_settings:
    label_col: "virus_host_name"
    exclude_labels: [ "nan" ]
    label_groupings:
      "Human": [ "Homo sapiens" ]
      "Pig": [ "Sus scrofa" ]
      "Capybara": [ "Hydrochoerus hydrochaeris" ]
      "Himalayan marmot": [ "Marmota himalayana" ]
      "Red junglefowl": [ "Gallus gallus" ]

  task_settings:
    - id: "prostt5_msl2048_fnn_2l_d1024_lr3e-4_itr4"
      name: "ProstT5"
      active: False
      mode: "train" # supported values: train, test
      fine_tuned_model_path: ""
      pre_trained_model_link: "Rostlab/ProstT5"
      hugging_face_cache_dir: "output/cache_dir"
      loss: "FocalLoss"
      n_mlp_layers: 2
      n_classes: 5
      input_dim: 1024 # input embedding dimension
      hidden_dim: 1024
      data_parallel: False

    - id: "prot_t5_xl_uniref50_msl2048_fnn_2l_d1024_lr3e-4_itr3"
      name: "ProtT5" # IMP: note the difference between ProstT5 and ProtT5
      active: True
      mode: "train" # supported values: train, test
      fine_tuned_model_path: ""
      pre_trained_model_link: "Rostlab/prot_t5_xl_uniref50"
      hugging_face_cache_dir: "output/cache_dir"
      loss: "FocalLoss"
      n_mlp_layers: 2
      n_classes: 5
      input_dim: 1024 # input embedding dimension
      hidden_dim: 1024
      data_parallel: False

    - id: "esm2_t12_35M_UR50D_bn_fnn_2l_d1024_lr1e-4_itr0"
      name: "ESM2"
      active: False
      mode: "train" # supported values: train, test
      fine_tuned_model_path: ""
      fine_tuned_model_name: "esm2_t12_35M_UR50D" # "esm2_t36_3B_UR50D" # "esm2_t48_15B_UR50D" # "esm2_t33_650M_UR50D"
      repr_layer: 12 # 36 # 48 # 33
      input_dim: 480 # 2560 # 5120 # 1280 # input embedding dimension
      loss: "FocalLoss"
      n_mlp_layers: 2
      n_classes: 5
      hidden_dim: 1024
      data_parallel: False

    - id: "esm3_msl2048_bn_fnn_2l_d1024_lr1e-4-itr1"
      name: "ESM3"
      active: False
      mode: "train" # supported values: train, test
      fine_tuned_model_name: "esm3-open"
      input_dim: 1536
      loss: "FocalLoss"
      n_mlp_layers: 2
      n_classes: 5
      hidden_dim: 1024
      data_parallel: False

output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "uniref90_embl_vertebrates_non_idv_t0.01_c5_seq_len_in_99.9percentile/20240131/host_multi/external"
  prefix: "uniref90viridae" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv
