config_type: "host_prediction" # options: data_preprocessor, host_prediction, evaluation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  perturbed_dataset_dir: "input/data/hev/perturbed_aligned/orf2"

classification_settings:
  model_type: "perturbed_dataset_prediction"  # options: baseline, nlp, perturbed_dataset_prediction
  type: "multi"
  sequence_settings:
    batch_size: 32
    id_col: "id"
    sequence_col: "sequence"
    max_sequence_length: 794 # max=794
    truncate: False
    pad_sequence_val: 0
    feature_type: "token"  # supported values 'kmer', 'cgr', 'token'
    kmer_settings:
      k: 3
    cgr_settings:
      img_size: 8
      img_dir: "input/data/coronaviridae/cgr_images"

  label_settings:
    label_col: "host"
    exclude_labels: [ "nan" ]
    label_groupings:
      "Human": [ "Human" ]
      "Boar": [ "Boar" ]
      "Others": [ "*" ] # Leporidae", "Rodent", "Avian", "Ferret", "Camel", "Mongoose", "Bat", "Primate", "Shrew", "Deer", "Hare", "Canine" ]
  models:
    - name: "fnn-l_10-lr1e-4"
      active: False
      mode: "test" # supported values: train, test
      model_path: ""
      loss: "FocalLoss"
      depth: 10
      n_tokens: 27
      n_classes: 3
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "cnn-l_4-lr1e-4"
      active: False
      mode: "test" # supported values: train, test
      model_path: "output/raw/hev/20231012/host_multi_e50/orf2/cnn-l_4-lr1e-3-orf2_itr0.pth"
      loss: "FocalLoss"
      depth: 4
      n_tokens: 27
      n_classes: 3
      n_epochs: 50
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      kernel_size: 3
      stride: 1
      manual_seed:  # whole numbers

    - name: "rnn-l_6-lr1e-4"
      active: False
      mode: "test" # supported values: train, test
      model_path: "output/raw/hev/20231012/host_multi_e50/orf2/rnn-l_6-lr1e-5-orf2_itr0.pth"
      loss: "FocalLoss"
      depth: 6 # number of rnn layers
      n_tokens: 27
      n_classes: 3
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "lstm-l_2-lr1e-4"
      active: False
      mode: "test" # supported values: train, test
      model_path: "output/raw/hev/20231012/host_multi_e50/orf2/lstm-l_2-lr1e-3-orf2_itr0.pth"
      loss: "FocalLoss"
      depth: 2
      n_tokens: 27
      n_classes: 3
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "transformer-l_6-h_8-lr1e-4"
      active: True
      mode: "test" # supported values: train, test
      model_path: "output/raw/hev/20231012/host_multi_e50/orf2/transformer-l_6-h_8-lr1e-4-orf2_itr0.pth"
      loss: "FocalLoss"
      with_convolution: False
      n_heads: 8
      depth: 6
      n_tokens: 27
      n_classes: 3
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "hev/20231017/perturbed_dataset_prediction/orf2-aligned/transformer-l_6-h_8-lr1e-4"
  prefix: "tf" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv