config_type: "host_prediction" # options: data_preprocessor, host_prediction, evaluation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/uniref90/20240131"

  # Name of file(s) in subdirectory to be read and processed.
  # Example: file_names: ["file_1.csv", "file_2.csv", "file_3.csv"]
  # file_names: [ "uniref90_final.csv" ]
  file_names: [ "uniref90_viridae_embl_hosts_pruned_metadata_species_vertebrates_w_seq_non_idv_t0.01_c5.csv" ]
  # seeds to split the files into training and testing
  # if provided, the number of seeds must match the number of iterations configured in classification_settings (n_iterations)
  split_seeds: [ 12612648, 31062180, 48918293, 55631155, 79221635 ]


classification_settings:
  experiment: "host_prediction"
  model_type: "baseline"
  n_iterations: 5
  split_input: True
  train_proportion: 0.8
  type: "multi"
  sequence_settings:
    batch_size: 64
    id_col: "uniref90_id"
    sequence_col: "seq"
    max_sequence_length: 1366 #3011 #1036 #624 # 6630 # 1024 # 1115
    truncate: True
    pad_token_val: 0
    feature_type: "pssm"  # supported values 'kmer' (additional parameter 'k' required) , 'pssm', 'token'
#    kmer_settings:
#      k: 3
  label_settings:
    label_col: "virus_host_name"
    exclude_labels: [ "nan"]
    label_groupings:
      "Human": [ "Homo sapiens" ]
      "Pig": [ "Sus scrofa" ]
      "Capybara": [ "Hydrochoerus hydrochaeris" ]
      "Himalayan marmot": [ "Marmota himalayana" ]
      "Red junglefowl": [ "Gallus gallus" ]
  models:
    - name: "lr"
      active: True
      C: [0.01, 0.1, 1]
      multiclass_type: "multinomial"

    - name: "rf"
      active: True
      n_estimators: [10, 100, 1000]
      max_depth: [3, 5]

output_settings:
  output_dir: "output"
  results_dir: "raw"
  visualizations_dir: "visualization"
  sub_dir: "uniref90_embl_vertebrates_non_idv_t0.01_c5/20240515/host_multi"
  prefix: "feature_pssm-lossfocalce_e50-msl1366" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv
