config_type: "transfer_learning" # options: data_preprocessor, host_prediction, evaluation
config_sub_type: "masked_language_modeling"

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/uniref90/20240131"

  # Name of file(s) in subdirectory to be read and processed.
  # Example: file_names: ["file_1.csv", "file_2.csv", "file_3.csv"]
  file_names: [ "uniref90_viridae.csv" ]
  # file_names: [ "uniref90_final.csv" ]
  # seeds to split the files into training and testing
  # if provided, the number of seeds must match the number of iterations configured in classification_settings (n_iterations)
  split_seeds: [ 12612648, 31062180, 48918293, 55631155, 79221635 ]

sequence_settings:
    batch_size: 128
    id_col: "uniref90_id"
    sequence_col: "seq"
    max_sequence_length: 128 # 6630 # 1024 # 1115
    truncate: False
    split_sequence: True
    pad_token_val: 0
    feature_type: "token"  # supported values 'kmer', 'cgr', 'token'

mlm_settings:
  no_mask_token_vals: [ 0 ]
  n_tokens: 26
  mask_prob: 0.15
  random_mask_prob: 0.1
  no_change_mask_prob: 0.1

encoder_settings:
  model_name: "transformer_encoder-l_6-h_8-cnv_k3s3_lr1e-4-mlm"
  embedding: "linear" # supported values are 'linear', 'convolution'
  n_heads: 8
  depth: 6
  input_dim: 512 # input embedding dimension
  hidden_dim: 1024
  kernel: 3
  stride: 3
  padding: 0

training_settings:
  experiment: "pre-training-mlm"
  n_iterations: 1
  split_input: True
  train_proportion: 0.8
  n_epochs: 30
  max_lr: 1e-4
  pct_start: 0.10
  div_factor: 25.0
  final_div_factor: 10000.0
  checkpoint_path: ""


output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "uniref90-viridae/pre-training/mlm/20240617"
  prefix: "mlm_tf_enc_l6_h8_lr1e-4_msl128_splitseq" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv
