config_type: "embedding_generation" # options: data_preprocessor, host_prediction, evaluation, transfer_learning, embedding_generation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/uniref90/20240131"
  # Name of file(s) in subdirectory to be read and processed.
  # Example: file_names: ["file_1.csv", "file_2.csv", "file_3.csv"]
  # file_names: [ "uniref90_final_msl1114.csv" ]
  file_names: [ "uniref90_viridae_embl_hosts_pruned_metadata_species_vertebrates_w_seq_idv.csv" ]
  # seeds to split the files into training and testing
  # if provided, the number of seeds must match the number of iterations configured in classification_settings (n_iterations)
  split_seeds: [ 12612648, 31062180, 48918293, 55631155, 79221635 ]

sequence_settings:
    batch_size: 16
    id_col: "uniref90_id"
    sequence_col: "seq"
    label_col: "virus_host_name"
    truncate: False
    feature_type: "token"  # supported values 'kmer', 'cgr', 'token'

pre_train_settings:
  encoder_settings:
    model_name: "transformer_encoder-l_6-h_8-lr1e-4-mlm"
    n_heads: 8
    depth: 6
    input_dim: 512 # input embedding dimension
    hidden_dim: 1024
    max_seq_len: 256

fine_tune_settings:
  task_settings:
    - id: "hybrid_attention_msl256s64ae_bn_cls_fnn_2l_d1024_lr3e-4"
      name: "VirProBERT"
      active: True
      fine_tuned_model_path: "output/raw/uniref90_embl_vertebrates_non_idv_t0.01_c5_seq_len_in_99.9percentile/20240826/host_multi/fine_tuning_hybrid_cls/mlm_tfenc_l6_h8_lr1e-4_uniref90viridae_msl256s64allemb_vs30cls_batchnorm_hybrid_attention_msl256s64ae_fnn_2l_d1024_lr1e-4_itr4.pth"
      segment_len: 256
      stride: 64
      cls_token: True
      n_heads: 8
      n_mlp_layers: 2
      n_classes: 5
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      data_parallel: False

output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "uniref90_embl_vertebrates_idv_all_hosts/20241125/host_multi/embedding"
  prefix: "mlm_tfenc_l6_h8_lr1e-4_uniref90viridae_vs30" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv
