config_type: "prediction" # options: data_preprocessor, prediction, evaluation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/hev/splits"

  # Name of file(s) in subdirectory to be read and processed.
  # Two forms of inputs:
  # Example: With pre split input files [NOTE: classification_settings.split_input MUST be set to False]
  #  file_names:
  #    - dir: "<dir_1>"
  #      train: ["train_file_1_1.csv", "train_file_1_2.csv", "train_file_1_3.csv"]
  #      test: ["test_file_1_1.csv", "test_file_1_2.csv", "test_file_1_3.csv"]
  #
  #    - dir: "<dir_2>"
  #      train: ["train_file_2_1.csv", "train_file_2_2.csv"]
  #      test: ["test_file_2_1.csv", "test_file_2_2.csv"]
  #
  # Example: Without presplit input files
  # file_names: ["file_1.csv", "file_2.csv", "file_3.csv"]
  file_names:
    - dir: "s10374872"
      train: [ "ORF1.fa_processed.csv_tr0.8_train.csv"]
      test: [ "ORF1.fa_processed.csv_tr0.8_test.csv"]

    - dir: "s44292027"
      train: [ "ORF1.fa_processed.csv_tr0.8_train.csv"]
      test: [ "ORF1.fa_processed.csv_tr0.8_test.csv"]

    - dir: "s224225183"
      train: [ "ORF1.fa_processed.csv_tr0.8_train.csv"]
      test: [ "ORF1.fa_processed.csv_tr0.8_test.csv"]

    - dir: "s331028508"
      train: [ "ORF1.fa_processed.csv_tr0.8_train.csv"]
      test: [ "ORF1.fa_processed.csv_tr0.8_test.csv"]

    - dir: "s752300722"
      train: [ "ORF1.fa_processed.csv_tr0.8_train.csv"]
      test: [ "ORF1.fa_processed.csv_tr0.8_test.csv"]


classification_settings:
  model_type: "nlp"
  n_iterations: 5
  split_input: False
  type: "multi"
  sequence_settings:
    batch_size: 16
    sequence_col: "sequence"
    max_sequence_length: 1800
    pad_sequence_val: 0
  label_settings:
    label_col: "host"
    exclude_labels: [ "culture supernatant (Unknown map)", "Unknown"]
    label_groupings:
      "Human" : ["Human"]
      "Boar": ["Boar"]
      "Others": ["*"]
  models:
    - name: "transformer"
      active: True
      mode: train # supported values: train, test
      pretrained_model_path: #"output/raw/uniref90/20230407/host_multi/trained_transformer_model.pth" # mandatory if the mode is set to test
      n_heads: 8
      depth: 6
      n_tokens: 27
      n_classes: 3
      n_epochs: 2
      dim: 512

output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "hev/20230418/host_multi/orf1"
  prefix: nlp # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv