# Input Settings: initialize base input folder names,
# dataset collections, and algorithms to run over
input_settings:

    # Denotes a list of datasets, each with the following parameters:
    #   name: Name of the dataset. May be used in logging or other
    #       messages written during execution
    #
    #   path: Relative path to the protein file
    datasets:
        "viprbrc_protein":
            path: "data/hep/2022-07-08-VipBRC-ORF-1-2-3-4-manual.fasta"
            rowNames: ["Accession", "Protein", "Host", "Genotype"]

    # Denotes a list of models to train/run
    models:
        # Classical bilstm language model from https://doi.org/10.1126/science.abd7331
        bilstm:
            active: false
            n_hidden: 3
            should_train: false
            seed: 556209273
            checkpoint: #"models/hepP1/hep-556209273-0.5.hdf5"
            epochs: 12

            # Same model as above, but different last layer classifier for transfer learning
            # Classifies 1/0 human/non-human
            bilstm_host:
                active: True
                epochs: 32
                n_hidden: 3
                embedding_dim: 20
                embed_targets: ["Protein", "Host", "Genotype"]
                embedding_cache: False
                should_train: False
                should_embed: False
                should_visualize_data: False
                train_split: 0.5
                batch_size: 64
                inf_batch_size: 144
                should_test: True
                transfer_learning: False
                checkpoint: "models/PTest/hepGenotypeTransferTrain-556209273-0.5.hdf5"
                targetKey: "Genotype"
                # e.g, the output heads would be ["Unknown", "HEV1", "HEV2", "HEV3", "HEV3ra", "HEV4", "HEV5", "HEV6", "HEV7"]
                targetNames: ["HEV1", "HEV2", "HEV3", "HEV3ra", "HEV4", "HEV5", "HEV6", "HEV7"]

# Output Settings: initialize base output folder names
output_settings:
    # Base output directory
    namespace: "hepGenotypeTransferTrain-556209273-0.5"
    output_dir: "output"

