# Input Settings: initialize base input folder names,
# dataset collections, and algorithms to run over
input_settings:

    # Denotes a list of datasets, each with the following parameters:
    #   name: Name of the dataset. May be used in logging or other
    #       messages written during execution
    #
    #   path: Relative path to the protein file
    datasets:
        - name: "viprbrc_protein"
          path: "data/hep/2022-07-08-VipBRC-ORF-1-2-3-4-manual.fasta"

    # Denotes a list of models to train/run
    models:
        # Classical bilstm language model from https://doi.org/10.1126/science.abd7331
        bilstm:
            should_train: false
            seed: 1
            checkpoint: "target/hep/checkpoints/bilstm/r1/bilstm_512-11.hdf5"

        # Same model as above, but different last layer classifier
        # Classifies 1/0 human/non-human
        bilstm_host:
            should_train: True
            seed: 1
            # If true, will use the weights from models.bilstm.checkpoint
            transfer_learning: True 
            # If undefined, will not transfer weights
            checkpoint: "" # "target/hep/checkpoints/bilstm_host/r1/bilstm_512-11.hdf5"
            split: .75 # Will do k-fold validation with skl

# Output Settings: initialize base output folder names
output_settings:
    # Base output directory
    output_dir: "outputs"
    output_prefix: "GSD"

