config_type: "host_prediction_perturbation" # options: data_preprocessor, host_prediction, evaluation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  perturbed_dataset_dir: "input/data/coronaviridae/20240313/wiv04/perturbed_dataset"

classification_settings:
  model_type: "perturbed_dataset_prediction"  # options: baseline, nlp, perturbed_dataset_prediction
  type: "multi"
  sequence_settings:
    batch_size: 16
    id_col: "id"
    sequence_col: "seq"
    max_sequence_length: 1366 # max=2169
    truncate: True
    pad_token_val: 0
    feature_type: "token"  # supported values 'kmer', 'cgr', 'token'
    kmer_settings:
      k: 3
    cgr_settings:
      img_size: 8
      img_dir: "input/data/coronaviridae/cgr_images"

  label_settings:
    label_col: "human_binary_label"
    exclude_labels: [ "nan"]
    label_groupings:
      "Human": [ "homo sapiens" ]
      "Non-Human": [ "NOT homo sapiens" ]
  models:
    - name: "transfer_learning_mlm_fnn_2l_lr1e-4"
      active: True
      mode: "test"
      model_path: "output/raw/coronaviridae_s_prot_embl_vertebrates_t0.01_c8/20240320/fine_tuning/host_prediction/binary/host_prediction_fnn_2l_d1024_lr1e-4_itr0.pth"
      depth: 2
      n_classes: 2
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      pre_train_settings:
        model_name: "transformer_encoder-l_6-h_8-lr1e-4-mlm"
        n_heads: 8
        depth: 6
        input_dim: 512 # input embedding dimension
        hidden_dim: 1024
        n_tokens: 26


output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "coronaviridae_s_prot_perturbation/20240320/WIV04/cov-S-binary-transfer_learning_mlm_fnn_2l_lr1e-4"
  prefix: "tl_tf_binary" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv