config_type: "host_prediction_runtime" # options: data_preprocessor, host_prediction, evaluation, host_prediction_runtime
config_sub_type: "external"

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  input_dir: "input/data/coronaviridae/20240313/sarscov2"
  input_file_name: "sarscov2_variants_spike_seqences_ncbivirus_20250106_downsampled.csv"

classification_settings:
  type: "multi"
  sequence_settings:
    batch_size: 1
    id_col: "accession_id"
    sequence_col: "seq"
    metadata_cols: ["pangolin_lineage", "geo_location", "seq_length"]
    truncate: False
    split: False
    feature_type: "token"  # supported values 'kmer', 'cgr', 'token'
    kmer_settings:
      k: 3
    cgr_settings:
      img_size: 8
      img_dir: "input/data/coronaviridae/cgr_images"

  label_settings:
    label_col: "virus_host_name"
    exclude_labels: [ "nan"]
    label_groupings:
      "Chicken": [ "gallus gallus" ]
      "Human": [ "homo sapiens" ]
      "Cat": [ "felis catus" ]
      "Pig": [ "sus scrofa" ]
      "Gray wolf": [ "canis lupus" ]
      "Horshoe bat": ["rhinolophus sp."]
      "Ferret": ["mustela putorius"]
      "Chinese rufous horseshoe bat": ["rhinolophus sinicus"]

  models:
    - id: "prostt5_bn_fnn_2l_d1024_lr3e-4"
      name: "ProstT5"
      active: True
      mode: "test" # supported values: train, test
      model_path: "output/raw/coronaviridae_s_prot_uniref90_embl_vertebrates_t0.01_c8/20241114/host_multi/external/uniref90coronaviridae_prostt5_msl2048_bn_fnn_2l_d1024_lr3e-4_itr4.pth"
      pre_trained_model_link: "Rostlab/ProstT5"
      hugging_face_cache_dir: "output/cache_dir"
      loss: "FocalLoss"
      n_mlp_layers: 2
      n_classes: 8
      input_dim: 1024 # input embedding dimension
      hidden_dim: 1024
      data_parallel: False

    - id: "esm2_t12_35M_UR50D_lr1e-4"
      name: "ESM2"
      active: False
      mode: "test" # supported values: train, test
      model_path: "output/raw/coronaviridae_s_prot_uniref90_embl_vertebrates_t0.01_c8/20241117/host_multi/virprobert/mlm_tfenc_l6_h8_lr1e-4_uniref90viridae_vs30_hybrid_attention_msl256s64ae_bn_cls_fnn_2l_d1024_lr3e-4_itr4.pth"
      fine_tuned_model_name: "esm2_t12_35M_UR50D" # "esm2_t36_3B_UR50D" # "esm2_t48_15B_UR50D" # "esm2_t33_650M_UR50D"
      repr_layer: 12 # 36 # 48 # 33
      input_dim: 480 # 2560 # 5120 # 1280 # input embedding dimension
      loss: "FocalLoss"
      n_mlp_layers: 2
      n_classes: 8
      hidden_dim: 1024
      data_parallel: False


output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "sarscov2_s_prot_variants/20250107/uniref90/external"
  prefix: "prostt5_bn_fnn_2l_d1024_lr3e-4" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv