config_type: "host_prediction" # options: data_preprocessor, host_prediction, evaluation

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  # Base input directory
  input_dir: "input/data/uniref90/20240131"

  # Name of file(s) in subdirectory to be read and processed.
  # Example: file_names: ["file_1.csv", "file_2.csv", "file_3.csv"]
  file_names: [ "uniref90_viridae_uniprot_hosts_pruned_metadata_species_vertebrates_w_seq.csv" ]
  # file_names: [ "uniref90_final.csv" ]
  # seeds to split the files into training and testing
  # if provided, the number of seeds must match the number of iterations configured in classification_settings (n_iterations)
  split_seeds: [ 12612648, 31062180, 48918293, 55631155, 79221635 ]


classification_settings:
  model_type: "nlp"
  n_iterations: 5
  split_input: True
  train_proportion: 0.8
  type: "multi"
  sequence_settings:
    batch_size: 64
    id_col: "uniref90_id"
    sequence_col: "seq"
    max_sequence_length: 1366 # 6630 # 1024 # 1115
    truncate: True
    pad_sequence_val: 0
    feature_type: "token"  # supported values 'kmer', 'cgr', 'token'
    kmer_settings:
      k: 3
    cgr_settings:
      img_size: 32
      img_dir: "input/data/uniref90/cgr_images"
  label_settings:
    label_col: "virus_host_name"
    exclude_labels: [ "nan" ]
    label_groupings:
      "Human": [ "Homo sapiens" ]
      "Desert warthog": [ "Phacochoerus aethiopicus" ]
      "Lesser bandicoot rat": [ "Bandicota bengalensis" ]
      "Horse": [ "Equus caballus" ]
      "Goat": [ "Capra hircus" ]
      "Red junglefowl": [ "Gallus gallus" ]
      "Wood mouse": [ "Apodemus sylvaticus" ]
      "Cattle": [ "Bos taurus" ]
      "Others": [ "*" ]
  training_settings:
    n_epochs: 50
    max_lr: 1e-3
    pct_start: 0.10
    div_factor: 25.0
    final_div_factor: 10000.0
  models:
    - name: "fnn-l_10-lr1e-3"
      active: True
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 10
      n_tokens: 27
      n_classes: 9
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "kmer-fnn-l_10"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 10
      n_tokens: 27
      n_classes: 9
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "cnn-l_4-lr1e-3"
      active: True
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 4
      n_tokens: 27
      n_classes: 9
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      kernel_size: 3
      stride: 1
      manual_seed:  # whole numbers

    - name: "cgr-cnn-l_2-lr1e-3"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 2
      n_tokens: 27
      n_classes: 9
      n_filters: 3
      kernel_size: 3
      stride: 1
      manual_seed:  # whole numbers

    - name: "cgr-cnn-pool-l_2-lr1e-3"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 2
      n_tokens: 27
      n_classes: 9
      n_filters: 16
      kernel_size: 3
      stride: 1
      manual_seed:  # whole numbers

    - name: "rnn-l_6-lr1e-5"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 6 # number of rnn layers
      n_tokens: 27
      n_classes: 9
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "lstm-l_2-lr1e-3"
      active: True
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      depth: 2
      n_tokens: 27
      n_classes: 9
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "transformer-l_6-h_8-lr1e-4"
      active: False
      mode: "train" # supported values: train, test
      loss: "FocalLoss"
      with_convolution: False
      n_heads: 8
      depth: 6
      n_tokens: 27
      n_classes: 9
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed:  # whole numbers

    - name: "transformer-conv-k4s4"
      active: False
      mode: "train" # supported values: train, test
      pretrained_model_path: #"output/raw/uniref90/20230407/host_multi/trained_transformer_model.pth" # mandatory if the mode is set to test
      loss: "FocalLoss"
      with_convolution: True # ensure that truncate is set to False in sequence_settings if convolution is being used
      kernel_size: 4
      stride: 4
      padding: 0
      n_heads: 8
      depth: 6
      n_tokens: 27
      n_classes: 9
      input_dim: 512 # input embedding dimension
      hidden_dim: 1024
      manual_seed: 0 # whole numbers
output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "uniref90-vertebrates/20240207/host_multi"
  prefix: "emb_sincos-d1024-lossfocalce_e50_msl1366" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv
