config_type: "host_prediction_perturbation" # options: data_preprocessor, host_prediction, evaluation
config_sub_type: "external"

# Input Settings:
  ## initialize base input folder name
  ## provide path to dataset folder
input_settings:
  perturbed_dataset_dir: "input/data/coronaviridae/20240313/sarscov2/uniprot/variants"

classification_settings:
  model_type: "perturbed_dataset_prediction"  # options: baseline, nlp, perturbed_dataset_prediction
  type: "multi"
  sequence_settings:
    batch_size: 32
    id_col: "id"
    sequence_col: "seq"
    max_sequence_length: 4096
    truncate: False
    split: False
    feature_type: "token"  # supported values 'kmer', 'cgr', 'token'
    kmer_settings:
      k: 3
    cgr_settings:
      img_size: 8
      img_dir: "input/data/coronaviridae/cgr_images"

  label_settings:
    label_col: "virus_host_name"
    exclude_labels: [ "nan"]
    label_groupings:
      "Pig": [ "sus scrofa" ]
      "Human": [ "homo sapiens" ]
      "Cat": [ "felis catus" ]
      "Dromedary camel": [ "camelus dromedarius" ]
      "Cattle": ["bos taurus"]
      "Chicken": [ "gallus gallus" ]
      "Gray wolf": [ "canis lupus" ]
      "Yak": [ "bos grunniens" ]

  models:
    - id: "prostt5_msl2048_bn_fnn_2l_d1024_lr3e-4"
      name: "ProstT5"
      active: True
      mode: "test" # supported values: train, test
      model_path: "output/raw/coronaviridae_s_prot_uniprot_embl_vertebrates_t0.01_c8/20241114/host_multi/external/uniprot_coronaviridae_prostt5_msl2048_bn_fnn_2l_d1024_lr3e-4_itr4.pth"
      pre_trained_model_link: "Rostlab/ProstT5"
      hugging_face_cache_dir: "output/cache_dir"
      loss: "FocalLoss"
      n_mlp_layers: 2
      n_classes: 8
      input_dim: 1024 # input embedding dimension
      hidden_dim: 1024
      data_parallel: False

output_settings:
  output_dir: "output"
  results_dir: "raw"
  sub_dir: "coronaviridae_s_prot_variants/20241118/sars-cov-2/uniprot/prostT5"
  prefix: "prostT5_lr3e-4_tl_tf_multi" # default: none; default file name = kmer_k<k>_lr_c<c>_<label>_<type>_tr<train_proportion>_n<n_iterations>_<output_prefix>_output.csv